### PR TITLE
[LMS-684] [API/Integration] My Learning Paths Tab

### PR DESCRIPTION
**Pull request by nicoleamber**
## Issue Link
[LMS-684 [API/Integration] [Trainee] My Learning Paths tab](https://framgiaph.backlog.com/view/LMS-684)

## Defintion of Done

- [x] Trainee should see enrolled learning paths in `My Learning Path` tab

## Steps to reproduce
1. Ensure that your account is a trainee and is enrolled in any Learning Path - you can do so in Django admin.
2. Go to `http://localhost:3000/trainee/dashboard` and click on My Learning Paths tab.

## Affected Components / Functionalities / Page
BE
- learning path view

FE
- trainee learning path section
- learning path API service

## Test Cases
_will update soon..._

## Notes
n/a

## Screenshots
[Screencast 2023-06-27 14-29-16.webm](https://github.com/framgia/sph-lms/assets/116238730/e9681c94-8c68-4658-adba-cd4176877539)

### CODE REVIEW

**Review by FranzDelosSantos — COMMENTED** [review]
Can you communicate with others about the folder structure?For me I think it is better to have same folder where the MyCourseSection are, so that it will be easy for others finding the trainee's myCourses and myLearningPath's code. The MyCourseSection is stored here sections/dashboard/trainee/CourseSection.tsx. 
ad122

**Review by Melanthonyando — COMMENTED** [review]
- Can you re-check this one , this is a kind of bug as well 

[Untitled_ Jun 27, 2023 5_35 PM.webm](https://github.com/framgia/sph-lms/assets/110366151/30ae80ae-bb8d-4e14-ae7c-172ac1d87198)

**Review by FranzDelosSantos — APPROVED** [review]
Iteration: 1
Comments: 1
Testing time: 25mins

**Review by Melanthonyando — APPROVED** [review]
### Approved 👍 

Iteration : 1
Comment: 1
Testing Time : 30 mins.

**Pull request merged**
