### PR TITLE
[LMS-350][FE][Markup]User List Page

### PR DESCRIPTION
**Pull request by epifaniovillaro**
## Issue Link
[LMS-350](https://framgiaph.backlog.com/view/LMS-350)

## Defintion of Done
- [x] place this in route /users/<:COMPANY_ID>/list
- [x] display the same design provided in the link
- [x] display all same fields. exclude "quick" column, and remove "login as user" button
- [x] exclude "Columns" button at the top
- [x] it must show "show per page" dropdown (must be dynamic and working)
- [x] it must show pagination (must be dynamic and working)
- [x] it must show "Showing 1 to 25 of 391 entries" dynamically
- [x] if no data in the list. It should display "no data found"

## Steps to reproduce
http://localhost:3000/users/1/list

## Affected Components / Functionalities / Page

- shared/components/Table/index.tsx
- shared/components/Pagination/index.tsx
- shared/utils/interface.tsx

## Test Cases
_will update soon..._

## Notes
n/a

## Screenshots
image
image
image

### CODE REVIEW

**Review by Marielleregner7 — APPROVED** [review]
**APPROVED**
- [ ] user list page is displayed and is identical to the inspo.
- [ ] shows per page, pagination, and Showing 1 to 10 of 100 entries dynamically.
- [x] Displays **No Data Found** if no data in the list.
- [x]  No ESLint warnings or errors.

Comments: 0
Test time: 65 mins
Iterations: 0

Proof:
userlistmarkup
image

**Review by FranzDelosSantos — COMMENTED** [review]
Please update the navbar, you can import the navbarlist the one I created that  can be found in 
image

**Review by FranzDelosSantos — APPROVED** [review]
Approved
- [ ] place this in route /users/<:COMPANY_ID>/list
- [ ] display the same design provided in the link
- [ ] display all same fields. exclude "quick" column, and remove "login as user" button
- [ ] exclude "Columns" button at the top
- [ ] it must show "show per page" dropdown (must be dynamic and working)
- [x] it must show pagination (must be dynamic and working)
- [x] it must show "Showing 1 to 25 of 391 entries" dynamically
- [x] if no data in the list. It should display "no data found"

Proof:
PrGood5

**Review by ragg09-sunasterisk — APPROVED** [review]

**Comment by ragg09-sunasterisk** [comment]
Comments: 1
Iterations: 1

**Pull request merged**
