### PR TITLE
[LMS-337][DOCKER] Fix client docker issues

### PR DESCRIPTION
**Pull request by kdacudag**
## Issue Link
https://framgiaph.backlog.com/view/LMS-337

## Definition of Done
- Be able to install/uninstall npm dependencies in both host and container.

### Installing dependencies in container :
- Remove previous containers and volumes
- Run `docker compose build --no-cache` to rebuild. No errors should be displayed
- Run `docker compose up`
- Install node packages via `docker exec -it lms-nextjs sh` and run `npm install`

### Installing dependencies in host:
- Install nvm for WSL first.
- Stop the containers
- Remove `client/node_modules` by running `sudo rm -rf client/node_modules`
- Use the node version the same as the container. 18.15.0. You can use nvm to update the node version.
- Run `npm install`
- If there's an error with permission, run: `sudo chmod -R 777 /client/node_modules`. Then run `npm install` again.
- To sync dependencies from container to host, npm install should be done in both host and container.

## Affected Components / Functionalities / Page
n/a

## Notes
- When adding packages for PR, only add instruction to `npm install` to install packages both locally and in the container that are in package.json but not yet installed. **Note** that the package name should no longer be required.

## Screenshots
n/a

### CODE REVIEW

**Review by Marielleregner7 — COMMENTED** [review]
Comment:

- The package did not reflect  in `node_modules`

image

**Review by ragg09-sunasterisk — COMMENTED** [review]
lms-nextjs stopped working resulting to unavailability of `docker exec -it lms-nextjs sh` and cant proceed running the npm install

Reference for docker-compose up
image

**Review by Marielleregner7 — APPROVED** [review]
**APPROVED**
- [ ] Packages are already reflected in the `node_modules`.
- [x] no problem/error encountered building the docker.
- [x] No ESLint error or warning.

Comments: 3
Test time: 80 mins
Iterations: 1

Proof:
image
image

**Comment by ragg09-sunasterisk** [comment]
Comments: 3
Iterations: 1

**Pull request merged**
