### PR TITLE
LMS-632 - [Markup] [Settings tab] Display settings tab in learning path detail page

### PR DESCRIPTION
**Pull request by Vali-R**
## Issue Link
https://framgiaph.backlog.com/view/LMS-632

## Definition of Done
- have edit setting button that allows trainer to edit context of learning path
- have inputs for name and description
- display list of courses  
- display toggle icon and expand course on click
- display archive button
- display add course button
- toggle edit mode
- have a modal for adding new course in a learning path based on the figma design
The modal should display:
    - Filter button
     - Search bar
     - List of courses (static)
     - Pagination
      - Cancel and add course buttons

## Affected Components / Functionalities / Page
 - client/features/learning-path/learningPathSlice.ts
 - client/features/tab/tabSlice.ts
 - client/src/pages/trainer/courses/index.tsx
 - client/src/pages/trainer/learning-paths/[id]/index.tsx
 - client/src/sections/courses/SettingsSection/EditSettingsButton.tsx
 - client/src/sections/courses/SettingsSection/index.tsx
 - client/src/sections/courses/create/AddLessonSection.tsx
 - client/src/sections/learning-paths/create/AddCourseSection.tsx
 - client/src/sections/learning-paths/create/CourseItem.tsx
 - client/src/sections/learning-paths/create/InitialSection.tsx
 - client/src/shared/components/Card/CourseCard/index.tsx
 - client/src/shared/components/Collapse/Collapse.tsx
 - client/src/shared/components/Tabs/index.tsx

## Screenshots
image

### CODE REVIEW

**Review by ejanton-sun — APPROVED** [review]
**Approved:**
Time: .5 hr
Comments: 0

**Review by Melanthonyando — COMMENTED** [review]
- The outside of the modal should be disabled , when modal is open , we already discussed this one by sir Jason

https://github.com/framgia/sph-lms/assets/110366151/a78b9cd1-aee0-43f6-8e2c-1cdd283e6daf


	- Please adjust width of the table of Course in List of courses. Please refer on the design : https://www.figma.com/file/6f92xbjEjJfQvwzbCTOWqF/TRAINING-PROGRAM-LMS?type=design&node-id=858-7593&t=Zxel4SHNyBCrPhzH-0

**Review by ejanton-sun — DISMISSED** [review]
# **Approved**

comments: 0
checking time: 0.5hr

**Review by Melanthonyando — APPROVED** [review]
Approved 

- Fixed all comments 
Proof :

https://github.com/framgia/sph-lms/assets/110366151/22eba1ee-bdf1-4012-8b23-a5130898d087


Comment : 1
Iteration : 1
Testing Time: 1hr.

**Review by ejanton-sun — APPROVED** [review]
# APrroved
Time: .2hr
Comments: 0

**Review by Melanthonyando — APPROVED** [review]
Approved 


Iteration: 1
Comment: 1
Testing Time:30mins.

**Pull request merged**
