### PR TITLE
[Setup] Dockerize apps

### PR DESCRIPTION
**Pull request by kdacudag**
## Definition of Done

- Be able to run docker compose build without errors
- Be able to run docker compose up without errors
- Be able to run pipenv commands
- Be able to run npm commands
- Be able to connect to MySQL using a client
- Be able to browse client in `localhost:3000`
- Be able to browse api in `localhost:8000`

## Steps to reproduce
- First, clone the repository in a different directory
- Follow steps in this PR's README.md

## Notes

- Django app has been replaced with the app that has pipenv

- Next.js app has been retained

### MySQL Connection
mysql_connection

### MySQL Tables
mysql_tables

### Migrations success
migrations_success

### Linter success
lint_success

### CODE REVIEW

**Review by escbooster12-dev — APPROVED** [review]
image
image

**Review by ragg09-sunasterisk — COMMENTED** [review]
image

image

image

**Review by ragg09-sunasterisk — APPROVED** [review]

**Comment by ragg09-sunasterisk** [comment]
Migration & Seeder Commands has no conflict in dockerize app

image

**Review by mikorosales — APPROVED** [review]
Approved

**Pull request merged**
