### PR TITLE
[LMS-346][BE] Sign In API

### PR DESCRIPTION
**Pull request by ragg09-sunasterisk**
## Issue Link
[LMS-346 [BE][API] Sign-in Page](https://framgiaph.backlog.com/view/LMS-346)

## Defintion of Done
* [x] one api for signing-in `/api/auth/sign-in`
* [x] one api to check if user is authenticated `/api/auth/user`. This api must return body properties (`token, name and email`) if the user is authenticated else it should return `401` status code
* [x] it must have backend validation
* [x] secure every end point
* [x] Email & password field required (cant user username to login anymore)

### Must Do
- run migration first
### Via postman
* Login : http://localhost:8000/api/auth/sign-in
-- test using form-data (use valid and invalid creds)
* API Health Check: http://localhost:8000/api/auth/user
-- pass Authorization : Token <token> in Header

## Affected Components / Functionalities / Page
n/a

## Test Cases
_will update soon..._

## Notes
 - I am currently using Username instead of just Name since the seeder and migration for the user model is not ready yet, will update this soon.

### Login
image
image
### API Health Check
image
image
### Test End Point
image

### CODE REVIEW

**Review by Marielleregner7 — APPROVED** [review]
**APPROVED**
- [ ]  Successfully authenticated the user using Postman.
- [ ]  returned body properties {token, name and email}.
- [ ] No ESLint warnings or errors.
- [x] No error found, when running npm run build.


Comments: 0
Test time: 76 mins
Iterations: 1

Proof:
sirrene
image

**Comment by escbooster12-dev** [comment]
* can we pass `email` instead of `username`. (please update migration if necessary)

**Review by mikorosales — APPROVED** [review]
image
image
image
image

**Review by mikorosales — APPROVED** [review]
- [x] Email is utilized instead of username
- [ ] Done checking in postman

image
image
image
image
image

**Review by Marielleregner7 — APPROVED** [review]
**APPROVED**
- [ ] Done rechecking, and it is now accepting email instead of the username.
- [ ] No ESLint warnings or errors.
- [ ] No error found, when running npm run build.

Comments: 4
Test time: 95 mins
Iterations: 2

Proof:

image

**Pull request merged**
